# Uncomment the next line to define a global platform for your project
 platform :ios, '8.1'

target 'Spike' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spike
  pod 'PNChart'
  pod 'SwiftyJSON', '~> 4.0'

  target 'SpikeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpikeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'widget' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for widget
  pod 'PNChart'
  pod 'SwiftyJSON', '~> 4.0'

end

target 'fswidget' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fswidget
  pod 'PNChart'
  pod 'SwiftyJSON', '~> 4.0'

end
